version: "3.7"

services:
  frontend:
    image: jwt_cases_frontend:latest
    container_name: jwt_cases_frontend
    ports:
      - ${FRONTEND_PORT}:22001

  backend:
    image: jwt_cases_backend:latest
    container_name: jwt_cases_backend
    ports:
      - ${SERVER_PORT}:21001
      - ${DEBUG_SERVER_PORT}:22229
    networks:
      - jwt_backend_network
    depends_on:
      - redis
      - postgres
      - pgbouncer

  redis:
    container_name: jwt_cases_redis
    image: redis:6.0.8-alpine
    networks:
      - backend_network
    command: redis-server --appendfsync always --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - jwt_redisdata:/data

  postgres:
    container_name: jwt_cases_postgres
    image: postgres:12
    networks:
      - jwt_backend_network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - jwt_pgdata:/var/lib/postgresql/data

  pgbouncer:
    container_name: jwt_cases_pgbouncer
    image: brainsam/pgbouncer:1.7.2
    networks:
      - jwt_backend_network
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_DATABASE_NAME}
      DB_HOST: postgres
      MAX_CLIENT_CONN: 10000
    ports:
      - ${DB_CONNECTION_PORT}:6432

networks:
  jwt_backend_network:
volumes:
  jwt_pgdata:
  jwt_redisdata:
