version: "3.7"

services:
  frontend:
    build:
      context: ./../src/frontend/main
      dockerfile: Dockerfile
    volumes:
      - ./../src/frontend/main:/app
      - /app/node_modules/

  backend:
    build:
      context: ./../src/backend/main
      dockerfile: Dockerfile
    volumes:
      - ./../src/backend/main:/usr/src/app
      - /usr/src/app/node_modules/

  postgres:
    ports:
      - ${DB_PORT}:5432
