version: "3.7"

services:
  frontend:
    build:
      context: ./../src/frontend/main
      dockerfile: Dockerfile
    volumes:
      - ./../src/frontend/main:/usr/src/app

  backend:
    build:
      context: ./../src/backend/main
      dockerfile: Dockerfile
    volumes:
      - ./../src/backend/main:/usr/src/app

  postgres:
    ports:
      - ${DB_PORT}:5432
